version: "3.9"

services:
  gateway: 
    build:
      context: .
      dockerfile: ./gateway/app.dockerfile
    depends_on: 
      - order
      - restaurant
      - user
    environment: 
      PORT: 8080
      ORDER_URL: order:3000
      USER_URL: user:3002
      RESTAURANT_URL: restaurant:3001
    ports:
      - 8080:8080
    restart: on-failure

  order:
    build:
      context: .
      dockerfile: ./order/app.dockerfile
    depends_on: 
      - order_db
    environment: 
      DATABASE_DSN: postgres://apple:123456@order_db/apple?sslmode=disable
      PORT: 3000
    ports: 
      - 3000:3000
    restart: on-failure

  restaurant:
    build: 
      context: .
      dockerfile: ./restaurant/app.dockerfile
    depends_on: 
      - restaurant_db
    environment:
      #"postgresql://%s:%s@%s:%d/%s?sslmode=disable", ds.DBUser, ds.DBPass, ds.Host, ds.Port, ds.DBName) 
      DATABASE_DSN: postgres://apple:123456@restaurant_db/apple?sslmode=disable
      PORT: 3001
    ports:
      - 3001:3001
    restart: on-failure

  user:
    build: 
      context: ./
      dockerfile: ./user/app.dockerfile
    depends_on: 
      - user_db
    environment: 
      DATABASE_DSN: postgres://apple:123456@user_db/apple?sslmode=disable
      PORT: 3002
    ports: 
      - 3002:3002
    restart: on-failure

  order_db:
    build:
      context: ./order
      dockerfile: ./db.dockerfile
    environment: 
      POSTGRES_DB: apple
      POSTGRES_USER: apple
      POSTGRES_PASSWORD: 123456
    restart: always

  restaurant_db:
    build:
      context: ./restaurant
      dockerfile: ./db.dockerfile
    environment: 
      POSTGRES_DB: apple
      POSTGRES_USER: apple
      POSTGRES_PASSWORD: 123456 
    restart: always

  user_db:
    build: 
      context: ./user
      dockerfile: ./db.dockerfile
    environment: 
      POSTGRES_DB: apple
      POSTGRES_USER: apple
      POSTGRES_PASSWORD: 123456
    restart: always
