version: "3.9"

services:
  traefik:
    image: traefik:v2.5.3
    restart: always
    command: --api.insecure=true --providers.docker
    networks:
      - proxy
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: traefik
    
networks:
  proxy:
    external: true
    driver: bridge